### ISSUE TITLE
List of admin groups

### ISSUE THREAD

**Issue by Zarquan** [wfau/esperia#12]
Different machines have different sets of admin groups.
Not all the machines have Docker, Libvirt and Ansible installed.

**Comment by Zarquan** [comment]
Turn this around, list the roles for each user.
```
logins:
    msh:
       groups:
           - 'root'
           - 'users'
           - 'libvirt'
           - 'docker'
           - 'ansible'
 ```    
The `root` and `ansible` groups also mean their ssh keys also get added to the `root` and `ansible` user accounts.
